#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#index:
#  path: /entry
#  controller: App\src\Controller\EntryController::index

app_logout:
  path: /logout
  methods: GET